function [TK,PmmHg,X1,X2,Y1,Y2] = importfileTERN_excel(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE2 Import data from a spreadsheet
%   [TK,PmmHg,X1,X2,Y1,Y2] = IMPORTFILE2(FILE) reads data from the first
%   worksheet in the Microsoft Excel spreadsheet file named FILE and
%   returns the data as column vectors.
%
%   [TK,PmmHg,X1,X2,Y1,Y2] = IMPORTFILE2(FILE,SHEET) reads from the
%   specified worksheet.
%
%   [TK,PmmHg,X1,X2,Y1,Y2] = IMPORTFILE2(FILE,SHEET,STARTROW,ENDROW) reads
%   from the specified worksheet for the specified row interval(s). Specify
%   STARTROW and ENDROW as a pair of scalars or vectors of matching size
%   for dis-contiguous row intervals. To read to the end of the file
%   specify an ENDROW of inf.%
% Example:
%   [TK,PmmHg,X1,X2,Y1,Y2] =
%   importfile2('Acet-CHCl3-meth2.xlsx','Acet-CHCl3-meth2',6,41);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/10/23 01:28:46

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 6;
    endRow = 41;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('A%d:F%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('A%d:F%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
TK = data(:,1);
PmmHg = data(:,2);
X1 = data(:,3);
X2 = data(:,4);
Y1 = data(:,5);
Y2 = data(:,6);

