function [TK,Pmmhg,X1,X2,X3,Y1,Y2,Y3,gamma_exp1,gamma_exp2,gamma_exp3,gamma_exp4] = importfile2(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE2 Import data from a spreadsheet
%   [TK,Pmmhg,X1,X2,X3,Y1,Y2,Y3,gamma_exp1,gamma_exp2,gamma_exp3,gamma_exp4]
%   = IMPORTFILE2(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as
%   column vectors.
%
%   [TK,Pmmhg,X1,X2,X3,Y1,Y2,Y3,gamma_exp1,gamma_exp2,gamma_exp3,gamma_exp4]
%   = IMPORTFILE2(FILE,SHEET) reads from the specified worksheet.
%
%   [TK,Pmmhg,X1,X2,X3,Y1,Y2,Y3,gamma_exp1,gamma_exp2,gamma_exp3,gamma_exp4]
%   = IMPORTFILE2(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [TK,Pmmhg,X1,X2,X3,Y1,Y2,Y3,gamma_exp1,gamma_exp2,gamma_exp3,gamma_exp4] = importfile2('quaternary1_GAMMA.xlsx','SHEET1',4,37);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/07/16 15:21:45

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 4;
    endRow = 37;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('A%d:L%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('A%d:L%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
TK = data(:,1);
Pmmhg = data(:,2);
X1 = data(:,3);
X2 = data(:,4);
X3 = data(:,5);
Y1 = data(:,6);
Y2 = data(:,7);
Y3 = data(:,8);
gamma_exp1 = data(:,9);
gamma_exp2 = data(:,10);
gamma_exp3 = data(:,11);
gamma_exp4 = data(:,12);

