function [TK1,PmmHg,X1,Y1] = importfile_EXCEL(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE2 Import data from a spreadsheet
%   [TK1,PmmHg,X1,Y1] = IMPORTFILE2(FILE) reads data from the first
%   worksheet in the Microsoft Excel spreadsheet file named FILE and
%   returns the data as column vectors.
%
%   [TK1,PmmHg,X1,Y1] = IMPORTFILE2(FILE,SHEET) reads from the specified
%   worksheet.
%
%   [TK1,PmmHg,X1,Y1] = IMPORTFILE2(FILE,SHEET,STARTROW,ENDROW) reads from
%   the specified worksheet for the specified row interval(s). Specify
%   STARTROW and ENDROW as a pair of scalars or vectors of matching size
%   for dis-contiguous row intervals. To read to the end of the file
%   specify an ENDROW of inf.%
% Example:
%   [TK1,PmmHg,X1,Y1] = importfile2('ACET-CHCL3.xlsx','Sheet1',3,35);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/10/20 01:44:24

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 3;
    endRow = 35;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('A%d:D%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('A%d:D%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
TK1 = data(:,1);
PmmHg = data(:,2);
X1 = data(:,3);
Y1 = data(:,4);

